### ISSUE TITLE
Proposal: Treadmill

### ISSUE THREAD

**Issue by anandology** [anandology/ideas#2]
Threadmill is a platform for creating guided projects with tasks which are auto verified. 

Threadmill allows the users to create a new project and add tasks with checks for each.

- A project will have a title, slug and a long description (markdown)
- There would be web interface to add/update/delete/reorder tasks
- Each task will have one or more checks (these can be written in yaml)
- A check would take a Validator and there would some built-in Validators like `http-validator`
- Additional validators can be added by specifying and API end point (train-search-validator)
- Good to have: update the project on git push -- we'll have a given an endpoint to update the project through API
- Login with email + magic link -- no password

**Comment by nikochiko** [comment]
What is the expected outcome of having a web interface?
  - Why this is important? We worked with local Pythons and YAMLs with CI/CD while working on Rajdhani. That worked well for us in order to create tasks and push them out - we could test our checks/tasks locally, fix typos and switch-up task order by working in YAML. It is unknown how much of it should be designated to the web ui now and if that would still be a good trainer experience.
  - If it is only to allow students to sign in and be connected, we can consider having a separate flow for creating projects than for working with them - with a connected git repo, for example.

**Comment by anandology** [comment]
One other requirement is the ability to host multiple projects in the same app.

**Comment by nikochiko** [comment]
> One other requirement is the ability to host multiple projects in the same app.

For cataloging?

**Comment by anandology** [comment]
The ideas of Threadmill will become part of capstone. Close this thread.
